### ISSUE TITLE
VQmod

### ISSUE THREAD

**Issue by MikhailShemelin** [sveawebpay/opencart-module#11]
Are there reasons to use VQmod instead of OCMod or is it just a part of legacy?

**Comment by KFoobar** [comment]
It's just legacy. However, you only need to use VQMod if you want to use our "Product Price Widget" on the product page to display monthly cost for partial payment etc.

**Comment by MikhailShemelin** [comment]
Thank you! 

If I remake it to OCMod or/and add other changes I consider potentially useful for other users, will you (or other contrubutors) be interested to have appropriate pull requests? What are the project policy/rules about (if any)?

**Comment by KFoobar** [comment]
You are welcome to submit a pull request, i'll review it and merge it if it's usable.

**Comment by MikhailShemelin** [comment]
That is clear. Thank you! 
I am closing the issue for now.
