### ISSUE TITLE
SimpleXMLElement::__construct(): Entity: line 1: parser error : Start tag expected, '<' not found 

### ISSUE THREAD

**Issue by danieljindev** [sveawebpay/opencart-module#12]
Svea Direct payment showing this error

Warning: SimpleXMLElement::__construct(): Entity: line 1: parser error : Start tag expected, '<' not found in ********public_html/svea/sveaekonomi/webpay/src/HostedService/HostedRequest.php on line 67Warning: SimpleXMLElement::__construct(): RESTEASY003870: Unable to extract parameter from http request: javax.ws.rs.FormP in ********public_html/svea/sveaekonomi/webpay/src/HostedService/HostedRequest.php on line 67Warning: SimpleXMLElement::__construct(): ^ in********public_html/svea/sveaekonomi/webpay/src/HostedService/HostedRequest.php on line 67
Svea response_error String could not be parsed as XML

**Comment by KFoobar** [comment]
Hi @danieljindev

- Can you describe how I can recreate the problem and exactly where the problem appears?
- Which version of OpenCart are you using?

**Comment by danieljindev** [comment]
I am using 3.0.3.6
When I select svea direct payment method and move to Confirm Order step(Step 6 on checkout page) it will occur and show above error.

**Comment by KFoobar** [comment]
Thank you, i'll investigate the issue.

**Comment by danieljindev** [comment]
I will very much appreciate your help. and could you please let me know when the following message will be shown? "Our technicians have been notified.
400 - Bad Request"

**Comment by KFoobar** [comment]
I don't succeed in recreating the problem myself.

Can you test with the following credentials and see if the issue persists:

Merchant ID: 
```
1200
```
Secret word:
```
27f18bfcbe4d7f39971cb3460fbe7234a82fb48f985cf22a068fa1a685fe7e6f93c7d0d92fee4e8fd7dc0c9f11e2507300e675
220ee85679afa681407ee2416d
```
