### ISSUE TITLE
I get this in the error log

### ISSUE THREAD

**Issue by Freakshows** [sveawebpay/opencart-module#3]
PHP Notice:  Undefined variable: svea_widget in ...../www/vqmod/vqcache/vq2-catalog_view_theme_default_template_product_product.tpl on line 221

**Comment by nlii** [comment]
Could you please tell me wich branch and version of the module you are using.

**Comment by Freakshows** [comment]
I'v had this event with both opencart-module-3.0.13 and now also with opencart-module-3.0.14.
I am running opencart version 2.0.3.1
