### ISSUE TITLE
i get this warning

### ISSUE THREAD

**Issue by diztie** [sveawebpay/opencart-module#4]
Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /storage/content/84/173884/jaktverket.se/public_html/admin/controller/payment/svea_partpayment.php on line 287Warning: file_get_contents(): Failed to enable crypto in /storage/content/84/173884/jaktverket.se/public_html/admin/controller/payment/svea_partpayment.php on line 287Warning: file_get_contents(https://raw.githubusercontent.com/sveawebpay/opencart-module/master/docs/info.json): failed to open stream: operation failed in /storage/content/84/173884/jaktverket.se/public_html/admin/controller/payment/svea_partpayment.php on line 287Notice: Trying to get property of non-object in /storage/content/84/173884/jaktverket.se/public_html/admin/controller/payment/svea_partpayment.php on line 290

**Comment by nlii** [comment]
The error appears when the module is trying to get content from github.
This post might help
https://help.github.com/articles/error-ssl-certificate-problem-verify-that-the-ca-cert-is-ok/
