### ISSUE TITLE
Parameterm1

### ISSUE THREAD

**Issue by driversshoppen** [sveawebpay/opencart-module#6]
Hello!
I have a issue
 PHP Warning:  Parameter 1 to ModelTotalSveafee::getTotal() expected to be a reference, value given in /storage/content/49/135549/driver.insamling.eu/public_html/vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php on line 150

How can i get this working?

**Comment by nlii** [comment]
Hello,
What version of Opencart, vqmod, PHP and Svea module are you using?

This is where the error occurs https://github.com/sveawebpay/opencart-module/blob/master/src/catalog/model/total/svea_fee.php#L13

**Comment by driversshoppen** [comment]
Im using opencart version 2.2.0.0, vqmod version 2.6.1, PHP 5.6 and svea Version 3.1.4

---
Mvh
Håkan Gundstedt
Härenstams EL & VVS AB
Instrumentvägen 9<x-apple-data-detectors://1/0>
553 02 Jönköping<x-apple-data-detectors://1/0>
hakan.g@harenstams.se<mailto:martin@harenstams.se>
Växel: 036-215 65 00<tel:036-215%2065%2000>
Dir: 036-215 65 06<tel:036-215%2065%2006>

Från: Anneli Halldn [mailto:notifications@github.com]
Skickat: den 26 maj 2016 08:06
Till: sveawebpay/opencart-module <opencart-module@noreply.github.com>
Kopia: Håkan Gundstedt <hakan.g@harenstams.se>; Author <author@noreply.github.com>
Ämne: Re: [sveawebpay/opencart-module] Parameterm1 (#6)


Hello,
What version of Opencart, vqmod, PHP and Svea module are you using?

This is where the error occurs https://github.com/sveawebpay/opencart-module/blob/master/src/catalog/model/total/svea_fee.php#L13

**Comment by nlii** [comment]
I see the function has changed to not taking a reference parameter in this version of Opencart. Thanks for reporting, 
The file catalog/model/total/svea_fee.php needs to be updated, so I recomend not using the Svea Invoice fee until this has a fix.

**Comment by driversshoppen** [comment]
Do you know when i can se a update for this or can you send me the update when its done.

---
Mvh
Håkan Gundstedt
Härenstams EL & VVS AB
Instrumentvägen 9<x-apple-data-detectors://1/0>
553 02 Jönköping<x-apple-data-detectors://1/0>
hakan.g@harenstams.se<mailto:martin@harenstams.se>
Växel: 036-215 65 00<tel:036-215%2065%2000>
Dir: 036-215 65 06<tel:036-215%2065%2006>

26 maj 2016 kl. 08:49 skrev Anneli Halldn <notifications@github.com<mailto:notifications@github.com>>:


I see the function has changed to not taking a reference parameter in this version of Opencart. Thanks for reporting,
The file catalog/model/total/svea_fee.php needs to be updated, so I recomend not using the Svea Invoice fee until this has a fix.

**Comment by nlii** [comment]
We will reference to this issue when we release the fix

**Comment by driversshoppen** [comment]
Ok!
Its the same problem with payex

---
Mvh
Håkan Gundstedt
Härenstams EL & VVS AB
Instrumentvägen 9<x-apple-data-detectors://1/0>
553 02 Jönköping<x-apple-data-detectors://1/0>
hakan.g@harenstams.se<mailto:martin@harenstams.se>
Växel: 036-215 65 00<tel:036-215%2065%2000>
Dir: 036-215 65 06<tel:036-215%2065%2006>

Från: Anneli Halldn [mailto:notifications@github.com]
Skickat: den 26 maj 2016 13:38
Till: sveawebpay/opencart-module <opencart-module@noreply.github.com>
Kopia: Håkan Gundstedt <hakan.g@harenstams.se>; Author <author@noreply.github.com>
Ämne: Re: [sveawebpay/opencart-module] Parameterm1 (#6)


We will reference to this issue when we release the fix

**Comment by driversshoppen** [comment]
How thos it going with this problem?

**Comment by nlii** [comment]
Hi, sorry for the delay. We now support Opencart 2.2
https://github.com/sveawebpay/opencart2-2-module
