### ISSUE TITLE
Problem with https and "get back to store"

### ISSUE THREAD

**Issue by tlombert** [sveawebpay/opencart-module#7]
Hi

We have some problem there our customers get aborted then they have done the payment and is going back to the store.

<img width="1081" alt="skarmavbild 2018-01-23 kl 14 21 03" src="https://user-images.githubusercontent.com/34110406/35294663-6bdf7b8c-0077-11e8-9e1f-20bb243d6060.png">

We have an SSL for that domain and that I can see/find is every setting ok in the store.

We use OpenCart 2.3.0.2 and Svea 4.1.0 and this was Direct_payment, but we have some problem with card_payment also.

Any suggestion where to start looking?

Store is; https://www.hyvlar.se

Best Regards
Thomas Lombert

**Comment by fre-sund** [comment]
Hi,

What is your HTTPS_SERVER variable set to in your config.php file (located in the root of opencart)

Best regards,
Fredrik Sundell

**Comment by tlombert** [comment]
Hi

Config.php
```
<?php
// HTTP
define('HTTP_SERVER', 'http://www.hyvlar.se/');

// HTTPS
define('HTTPS_SERVER', 'https://www.hyvlar.se/');

// DIR
```

Admin/config.php
```
<?php
// HTTP
define('HTTP_SERVER', 'http://www.hyvlar.se/admin/');
define('HTTP_CATALOG', 'http://www.hyvlar.se/');

// HTTPS
define('HTTPS_SERVER', 'https://www.hyvlar.se/admin/');
define('HTTPS_CATALOG', 'https://www.hyvlar.se/');

// DIR
```

<img width="582" alt="skarmavbild 2018-01-24 kl 10 36 58" src="https://user-images.githubusercontent.com/34110406/35324933-8dbe1c56-00f2-11e8-8a9f-d4639be17dca.png">

Is there any more places with SSL settings?

Best Regards
Thomas

**Comment by fre-sund** [comment]
Can you check what value 'config_secure' has in your database? Is SSL enabled in the OpenCart admin? You can find the option in System->Settings->Store->Edit->Server->Security

**Comment by fre-sund** [comment]
Can you check what value 'config_secure' has in the settings table in your database?

**Comment by tlombert** [comment]
<img width="1065" alt="skarmavbild 2018-01-24 kl 11 00 14" src="https://user-images.githubusercontent.com/34110406/35326064-cf775d26-00f5-11e8-8bbb-9c3b40f7b2f5.png">

**Comment by fre-sund** [comment]
If you set it to 1 it should work. Is config_ssl set to 1? We probably have to change which value we check for in the module.

**Comment by tlombert** [comment]
This is sorted in key;

<img width="1141" alt="skarmavbild 2018-01-24 kl 11 07 06" src="https://user-images.githubusercontent.com/34110406/35326402-da57fdd0-00f6-11e8-9a1d-41d9d23058db.png">

**Comment by fre-sund** [comment]
And config_url? None of those seem to have hyvlar in it's url.

**Comment by tlombert** [comment]
<img width="1140" alt="skarmavbild 2018-01-24 kl 11 10 07" src="https://user-images.githubusercontent.com/34110406/35326502-2e11cb40-00f7-11e8-8a09-4acb73ab0e95.png">

**Comment by fre-sund** [comment]
That's odd. Can you try a new transaction now that you've changed config_secure to 1?

**Comment by tlombert** [comment]
But Store1 has config_secure = 1 already. First I did not see that it was one setting for every store..

I have not change anything..

**Comment by fre-sund** [comment]
Which store is hylvar? Store 1 seem to have it set to 0:
![bild](https://user-images.githubusercontent.com/19384773/35326970-8df7f9f2-00f8-11e8-96c1-b33ca4c7008f.png)

**Comment by tlombert** [comment]
Store 0 = hyvlar.se
Store 1 = tools4wood.se
Store 2 = hoylat.fi
Store 3 = hantverksklader.shop
Store 4 = rubank.se

**Comment by tlombert** [comment]
<img width="790" alt="skarmavbild 2018-01-24 kl 11 21 53" src="https://user-images.githubusercontent.com/34110406/35327068-d6b9f532-00f8-11e8-86e1-80757a536531.png">

**Comment by tlombert** [comment]
I get the feeling that the url is wrong then I get back to the store; 
<img width="611" alt="skarmavbild 2018-01-24 kl 10 51 58" src="https://user-images.githubusercontent.com/34110406/35327113-0521c83c-00f9-11e8-914f-eaa90e6f96b8.png">
<img width="1030" alt="skarmavbild 2018-01-24 kl 10 52 38" src="https://user-images.githubusercontent.com/34110406/35327118-0cd71e10-00f9-11e8-8a84-aa408f543f27.png">

Should it not be https://www.hyvlar.se/index.php? .. ..

**Comment by tlombert** [comment]
This is from SEB direct_payment..

**Comment by fre-sund** [comment]
Ahh, that explains it.. Just checked the code, only card transactions seem to handle SSL correctly. I'll have to change the code for directbank.

Can you try a card payment and see if it works properly? In that case I can just push a quick fix for directbank.

**Comment by tlombert** [comment]
Ok. I will try.

**Comment by tlombert** [comment]
Yes, no problem there;

<img width="691" alt="skarmavbild 2018-01-24 kl 11 31 20" src="https://user-images.githubusercontent.com/34110406/35327551-2a46344e-00fa-11e8-85e5-efb5d5b083fc.png">

**Comment by fre-sund** [comment]
I've released a fix for this issue: https://github.com/sveawebpay/opencart-module/releases/tag/v4.1.47

Please get back to me after you've tried it and I'll close this issue.

**Comment by tlombert** [comment]
And here is a direct_payment;
<img width="534" alt="skarmavbild 2018-01-24 kl 12 15 20" src="https://user-images.githubusercontent.com/34110406/35329489-5daa06fc-0100-11e8-9253-749ee6d08dc1.png">

It looks everything now works!

Thanks!
/Thomas

**Comment by fre-sund** [comment]
Thank you for confirming it, ill close the issue now.

Best regards,
Fredrik
